export { default as AboutAgency } from '../..\\components\\AboutAgency.vue'
export { default as AboutAuthenticStudio } from '../..\\components\\AboutAuthenticStudio.vue'
export { default as AboutBreadcrumb } from '../..\\components\\AboutBreadcrumb.vue'
export { default as AboutBreadcrumbFour } from '../..\\components\\AboutBreadcrumbFour.vue'
export { default as AboutBreadcrumbThree } from '../..\\components\\AboutBreadcrumbThree.vue'
export { default as AboutSkill } from '../..\\components\\AboutSkill.vue'
export { default as AccordionStyleOne } from '../..\\components\\AccordionStyleOne.vue'
export { default as AccordionStyleTwo } from '../..\\components\\AccordionStyleTwo.vue'
export { default as AgencyCounterup } from '../..\\components\\AgencyCounterup.vue'
export { default as AlbumList } from '../..\\components\\AlbumList.vue'
export { default as BestService } from '../..\\components\\BestService.vue'
export { default as BlogPost } from '../..\\components\\BlogPost.vue'
export { default as BlogPostFour } from '../..\\components\\BlogPostFour.vue'
export { default as BlogPostThree } from '../..\\components\\BlogPostThree.vue'
export { default as BlogPostTwo } from '../..\\components\\BlogPostTwo.vue'
export { default as BlogRestaurant } from '../..\\components\\BlogRestaurant.vue'
export { default as BlogSidebar } from '../..\\components\\BlogSidebar.vue'
export { default as BrandLogoCarousel } from '../..\\components\\BrandLogoCarousel.vue'
export { default as BrandLogoCarouselCustom } from '../..\\components\\BrandLogoCarouselCustom.vue'
export { default as BrandLogoCarouselWithNavigation } from '../..\\components\\BrandLogoCarouselWithNavigation.vue'
export { default as BrandLogoStyleOne } from '../..\\components\\BrandLogoStyleOne.vue'
export { default as BrandLogoWithoutCarousel } from '../..\\components\\BrandLogoWithoutCarousel.vue'
export { default as Breadcrumb } from '../..\\components\\Breadcrumb.vue'
export { default as CallToAction } from '../..\\components\\CallToAction.vue'
export { default as CareerItem } from '../..\\components\\CareerItem.vue'
export { default as ContactForm } from '../..\\components\\ContactForm.vue'
export { default as ContactUsBreadcrumb } from '../..\\components\\ContactUsBreadcrumb.vue'
export { default as ContactUsOne } from '../..\\components\\ContactUsOne.vue'
export { default as ContactUsThree } from '../..\\components\\ContactUsThree.vue'
export { default as ContactUsTwo } from '../..\\components\\ContactUsTwo.vue'
export { default as CurveShape } from '../..\\components\\CurveShape.vue'
export { default as EffectiveSolution } from '../..\\components\\EffectiveSolution.vue'
export { default as EssentialCaseStudy } from '../..\\components\\EssentialCaseStudy.vue'
export { default as EssentialIconBox } from '../..\\components\\EssentialIconBox.vue'
export { default as EssentialService } from '../..\\components\\EssentialService.vue'
export { default as EssentialSkillProgress } from '../..\\components\\EssentialSkillProgress.vue'
export { default as EssentialTestimonial } from '../..\\components\\EssentialTestimonial.vue'
export { default as FeaturedProjects } from '../..\\components\\FeaturedProjects.vue'
export { default as FeatureItemStyleOne } from '../..\\components\\FeatureItemStyleOne.vue'
export { default as Firefly } from '../..\\components\\Firefly.vue'
export { default as FlexibleSlider } from '../..\\components\\FlexibleSlider.vue'
export { default as FlexibleSliderFive } from '../..\\components\\FlexibleSliderFive.vue'
export { default as FlexibleSliderFour } from '../..\\components\\FlexibleSliderFour.vue'
export { default as FlexibleSliderThree } from '../..\\components\\FlexibleSliderThree.vue'
export { default as FlexibleSliderTwo } from '../..\\components\\FlexibleSliderTwo.vue'
export { default as Footer } from '../..\\components\\Footer.vue'
export { default as FooterAgency } from '../..\\components\\FooterAgency.vue'
export { default as FooterStyleFour } from '../..\\components\\FooterStyleFour.vue'
export { default as FooterStyleThree } from '../..\\components\\FooterStyleThree.vue'
export { default as FooterTwo } from '../..\\components\\FooterTwo.vue'
export { default as GoogleMap } from '../..\\components\\GoogleMap.vue'
export { default as GradationOne } from '../..\\components\\GradationOne.vue'
export { default as Header } from '../..\\components\\Header.vue'
export { default as HeaderAbout } from '../..\\components\\HeaderAbout.vue'
export { default as HeaderBlack } from '../..\\components\\HeaderBlack.vue'
export { default as HeaderBlackTransparentWithSocial } from '../..\\components\\HeaderBlackTransparentWithSocial.vue'
export { default as HeaderElement } from '../..\\components\\HeaderElement.vue'
export { default as HeaderForOffCanvas } from '../..\\components\\HeaderForOffCanvas.vue'
export { default as HeaderForOffCanvasBlack } from '../..\\components\\HeaderForOffCanvasBlack.vue'
export { default as HeaderOnepage } from '../..\\components\\HeaderOnepage.vue'
export { default as HeaderPortfolioSlider } from '../..\\components\\HeaderPortfolioSlider.vue'
export { default as HeaderTransparentWithSocial } from '../..\\components\\HeaderTransparentWithSocial.vue'
export { default as HeaderVerticalOffcanvas } from '../..\\components\\HeaderVerticalOffcanvas.vue'
export { default as HeaderVerticalRestaurant } from '../..\\components\\HeaderVerticalRestaurant.vue'
export { default as HeaderVerticle } from '../..\\components\\HeaderVerticle.vue'
export { default as HeroAgency } from '../..\\components\\HeroAgency.vue'
export { default as HeroAuthenticStudio } from '../..\\components\\HeroAuthenticStudio.vue'
export { default as HeroBusiness } from '../..\\components\\HeroBusiness.vue'
export { default as HeroDesignStudio } from '../..\\components\\HeroDesignStudio.vue'
export { default as HeroDigitalAgency } from '../..\\components\\HeroDigitalAgency.vue'
export { default as HeroEssential } from '../..\\components\\HeroEssential.vue'
export { default as HeroFullscreen } from '../..\\components\\HeroFullscreen.vue'
export { default as HeroIndieMusician } from '../..\\components\\HeroIndieMusician.vue'
export { default as HeroLanding } from '../..\\components\\HeroLanding.vue'
export { default as HeroMinimalAgency } from '../..\\components\\HeroMinimalAgency.vue'
export { default as HeroOnepage } from '../..\\components\\HeroOnepage.vue'
export { default as HeroPhotoSliderGallery } from '../..\\components\\HeroPhotoSliderGallery.vue'
export { default as HeroPortfolioSlide } from '../..\\components\\HeroPortfolioSlide.vue'
export { default as HeroProductLanding } from '../..\\components\\HeroProductLanding.vue'
export { default as HeroRestaurant } from '../..\\components\\HeroRestaurant.vue'
export { default as HeroService } from '../..\\components\\HeroService.vue'
export { default as HeroStartUp } from '../..\\components\\HeroStartUp.vue'
export { default as HeroVertical } from '../..\\components\\HeroVertical.vue'
export { default as IconBoxItemOne } from '../..\\components\\IconBoxItemOne.vue'
export { default as InstagramPost } from '../..\\components\\InstagramPost.vue'
export { default as MinimalMetroGrid } from '../..\\components\\MinimalMetroGrid.vue'
export { default as MobileNavigation } from '../..\\components\\MobileNavigation.vue'
export { default as MotivationalArchive } from '../..\\components\\MotivationalArchive.vue'
export { default as MusicianBlog } from '../..\\components\\MusicianBlog.vue'
export { default as MusicianCountdown } from '../..\\components\\MusicianCountdown.vue'
export { default as MusicianCounterup } from '../..\\components\\MusicianCounterup.vue'
export { default as MusicianGallery } from '../..\\components\\MusicianGallery.vue'
export { default as MusicianIconBox } from '../..\\components\\MusicianIconBox.vue'
export { default as MusicianMixTapes } from '../..\\components\\MusicianMixTapes.vue'
export { default as MusicianPortfolioGallery } from '../..\\components\\MusicianPortfolioGallery.vue'
export { default as Navigation } from '../..\\components\\Navigation.vue'
export { default as NewsletterCta } from '../..\\components\\NewsletterCta.vue'
export { default as OffcanvasMenu } from '../..\\components\\OffcanvasMenu.vue'
export { default as OffCanvasMobileMenu } from '../..\\components\\OffCanvasMobileMenu.vue'
export { default as OnepageTeammember } from '../..\\components\\OnepageTeammember.vue'
export { default as PortfolioItemCaptionBottom } from '../..\\components\\PortfolioItemCaptionBottom.vue'
export { default as PortfolioItemCenterCaption } from '../..\\components\\PortfolioItemCenterCaption.vue'
export { default as PricingItemStyleOne } from '../..\\components\\PricingItemStyleOne.vue'
export { default as PricingItemStyleTwo } from '../..\\components\\PricingItemStyleTwo.vue'
export { default as ProductTab } from '../..\\components\\ProductTab.vue'
export { default as SearchPopup } from '../..\\components\\SearchPopup.vue'
export { default as ServiceAgency } from '../..\\components\\ServiceAgency.vue'
export { default as ServiceClassicBreadcrumb } from '../..\\components\\ServiceClassicBreadcrumb.vue'
export { default as ServiceItemOne } from '../..\\components\\ServiceItemOne.vue'
export { default as ServiceItemOneWithoutButton } from '../..\\components\\ServiceItemOneWithoutButton.vue'
export { default as ServiceItemStyleTwo } from '../..\\components\\ServiceItemStyleTwo.vue'
export { default as ServiceModern } from '../..\\components\\ServiceModern.vue'
export { default as ServiceModernBreadcrumb } from '../..\\components\\ServiceModernBreadcrumb.vue'
export { default as TabOne } from '../..\\components\\TabOne.vue'
export { default as TabVertical } from '../..\\components\\TabVertical.vue'
export { default as TeamCarouselFull } from '../..\\components\\TeamCarouselFull.vue'
export { default as TeamMemberOne } from '../..\\components\\TeamMemberOne.vue'
export { default as TeamMemberThree } from '../..\\components\\TeamMemberThree.vue'
export { default as TeamMemberTwo } from '../..\\components\\TeamMemberTwo.vue'
export { default as TestimonialItem } from '../..\\components\\TestimonialItem.vue'
export { default as TestimonialSix } from '../..\\components\\TestimonialSix.vue'
export { default as VideoOne } from '../..\\components\\VideoOne.vue'
export { default as VideoService } from '../..\\components\\VideoService.vue'
export { default as WhatWeDo } from '../..\\components\\WhatWeDo.vue'
export { default as WhatWeDoTwo } from '../..\\components\\WhatWeDoTwo.vue'
export { default as AboutServiceItemOneWithoutButton } from '../..\\components\\about\\ServiceItemOneWithoutButton.vue'
export { default as AboutServiceTwo } from '../..\\components\\about\\ServiceTwo.vue'
export { default as AboutWhatWeDoThree } from '../..\\components\\about\\WhatWeDoThree.vue'
export { default as ContactMobileNavigation } from '../..\\components\\contact\\MobileNavigation.vue'
export { default as ContactNavigation } from '../..\\components\\contact\\Navigation.vue'
export { default as ContactOffcanvasMenu } from '../..\\components\\contact\\OffcanvasMenu.vue'
export { default as ContactOffCanvasMobileMenu } from '../..\\components\\contact\\OffCanvasMobileMenu.vue'
export { default as EventsExpandableImage } from '../..\\components\\events\\ExpandableImage.vue'
export { default as EventsHeaderVerticle } from '../..\\components\\events\\HeaderVerticle.vue'
export { default as EventsHeroFullscreen } from '../..\\components\\events\\HeroFullscreen.vue'
export { default as EventsMobileNavigation } from '../..\\components\\events\\MobileNavigation.vue'
export { default as EventsNavigation } from '../..\\components\\events\\Navigation.vue'
export { default as EventsOffCanvasMobileMenu } from '../..\\components\\events\\OffCanvasMobileMenu.vue'
export { default as LandingContactUsThree } from '../..\\components\\landing\\ContactUsThree.vue'
export { default as LandingCurveShape } from '../..\\components\\landing\\CurveShape.vue'
export { default as LandingEssentialService } from '../..\\components\\landing\\EssentialService.vue'
export { default as LandingEssentialTestimonial1 } from '../..\\components\\landing\\EssentialTestimonial1.vue'
export { default as LandingEssentialTestimonial2 } from '../..\\components\\landing\\EssentialTestimonial2.vue'
export { default as LandingEventsItemCaptionCenter } from '../..\\components\\landing\\EventsItemCaptionCenter.vue'
export { default as LandingFlexibleSliderFour } from '../..\\components\\landing\\FlexibleSliderFour.vue'
export { default as LandingFooterTwo } from '../..\\components\\landing\\FooterTwo.vue'
export { default as LandingHeaderForOffCanvas } from '../..\\components\\landing\\HeaderForOffCanvas.vue'
export { default as LandingHeroService } from '../..\\components\\landing\\HeroService.vue'
export { default as LandingMobileNavigation } from '../..\\components\\landing\\MobileNavigation.vue'
export { default as LandingNavigation } from '../..\\components\\landing\\Navigation.vue'
export { default as LandingOffcanvasMenu } from '../..\\components\\landing\\OffcanvasMenu.vue'
export { default as LandingOffCanvasMobileMenu } from '../..\\components\\landing\\OffCanvasMobileMenu.vue'
export { default as LandingPortfolioItemCenterCaption } from '../..\\components\\landing\\PortfolioItemCenterCaption.vue'
export { default as LandingPortfolioItemFilter } from '../..\\components\\landing\\PortfolioItemFilter.vue'
export { default as LandingServiceCarousel } from '../..\\components\\landing\\ServiceCarousel.vue'
export { default as SectionsAccordionOne } from '../..\\components\\sections\\AccordionOne.vue'
export { default as SectionsBlogOne } from '../..\\components\\sections\\BlogOne.vue'
export { default as SectionsBlogThree } from '../..\\components\\sections\\BlogThree.vue'
export { default as SectionsBlogTwo } from '../..\\components\\sections\\BlogTwo.vue'
export { default as SectionsCarouselWithCaptionOne } from '../..\\components\\sections\\CarouselWithCaptionOne.vue'
export { default as SectionsCarouselWithCaptionTwo } from '../..\\components\\sections\\CarouselWithCaptionTwo.vue'
export { default as SectionsContactModern } from '../..\\components\\sections\\ContactModern.vue'
export { default as SectionsCounterUpOne } from '../..\\components\\sections\\CounterUpOne.vue'
export { default as SectionsCounterUpTwo } from '../..\\components\\sections\\CounterUpTwo.vue'
export { default as SectionsFeaturesOne } from '../..\\components\\sections\\FeaturesOne.vue'
export { default as SectionsFeatureStartUp } from '../..\\components\\sections\\FeatureStartUp.vue'
export { default as SectionsOurServiceOne } from '../..\\components\\sections\\OurServiceOne.vue'
export { default as SectionsPortfolioItemFilter } from '../..\\components\\sections\\PortfolioItemFilter.vue'
export { default as SectionsPortfolioOne } from '../..\\components\\sections\\PortfolioOne.vue'
export { default as SectionsPortfolioTwo } from '../..\\components\\sections\\PortfolioTwo.vue'
export { default as SectionsPricingOne } from '../..\\components\\sections\\PricingOne.vue'
export { default as SectionsServiceCarousel } from '../..\\components\\sections\\ServiceCarousel.vue'
export { default as SectionsServiceIconBoxOne } from '../..\\components\\sections\\ServiceIconBoxOne.vue'
export { default as SectionsServiceIconBoxTwo } from '../..\\components\\sections\\ServiceIconBoxTwo.vue'
export { default as SectionsServiceIconBoxWithTitle } from '../..\\components\\sections\\ServiceIconBoxWithTitle.vue'
export { default as SectionsServiceIconBoxWithTitleStleTwo } from '../..\\components\\sections\\ServiceIconBoxWithTitleStleTwo.vue'
export { default as SectionsServiceOne } from '../..\\components\\sections\\ServiceOne.vue'
export { default as SectionsServiceTwo } from '../..\\components\\sections\\ServiceTwo.vue'
export { default as SectionsStartUpStratagy } from '../..\\components\\sections\\StartUpStratagy.vue'
export { default as SectionsTeamFour } from '../..\\components\\sections\\TeamFour.vue'
export { default as SectionsTeamOne } from '../..\\components\\sections\\TeamOne.vue'
export { default as SectionsTeamThree } from '../..\\components\\sections\\TeamThree.vue'
export { default as SectionsTeamTwo } from '../..\\components\\sections\\TeamTwo.vue'
export { default as SectionsTestimonialFive } from '../..\\components\\sections\\TestimonialFive.vue'
export { default as SectionsTestimonialFour } from '../..\\components\\sections\\TestimonialFour.vue'
export { default as SectionsTestimonialOne } from '../..\\components\\sections\\TestimonialOne.vue'
export { default as SectionsTestimonialThree } from '../..\\components\\sections\\TestimonialThree.vue'
export { default as SectionsTestimonialTwo } from '../..\\components\\sections\\TestimonialTwo.vue'
export { default as SectionsTestimonialWithoutCarousel } from '../..\\components\\sections\\TestimonialWithoutCarousel.vue'
export { default as SectionsWhatWeDoThree } from '../..\\components\\sections\\WhatWeDoThree.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
